<a href="https://colab.research.google.com/github/KrishDhanani/PyTorch_DeepLearning/blob/main/001_PyTorch_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

This is **First** file of course :)

In [1]:
print("I'm excited to write PyTorch code!")

I'm excited to write PyTorch code!


In [2]:
import torch
print(torch.__version__)
# You can chnage btw CPU, GPU AND TPU: Runtime -> Change runtime type

2.11.0+cpu


In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## Introduction to Tensors

### Creating tensors


PyTorch tensors are created using 'torch.Tensor()' -= https://docs.pytorch.org/docs/main/tensors.html

In [4]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim

0

In [6]:
# Get tensor back as python int
scalar.item()

7

In [7]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [10]:
# MATRIX
MATRIX = torch.tensor([[7,8],
                       [8,9]])
MATRIX

tensor([[7, 8],
        [8, 9]])

In [11]:
MATRIX.ndim   # Dimentions like square breacket in the tensor

2

In [12]:
MATRIX[0]

tensor([7, 8])

In [13]:
MATRIX.shape

torch.Size([2, 2])

In [14]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [3,4,5],
                        [4,5,6]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 4, 5],
         [4, 5, 6]]])

In [15]:
TENSOR.ndim

3

In [16]:
TENSOR.shape

torch.Size([1, 3, 3])

# Random Tensors

Why random tensors?

Random tensors are important bcs the way many neural network learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data ->update random numbers -> look at data -> update random numbers`

Torch random tensors - https://docs.pytorch.org/docs/main/generated/torch.rand.html#torch-rand

In [17]:
# Creat Random Tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.8781, 0.5989, 0.8516, 0.1029],
        [0.6289, 0.7742, 0.5533, 0.8855],
        [0.5224, 0.7340, 0.7495, 0.3445]])

In [18]:
random_tensor.ndim

2

In [19]:
random_tensor = torch.rand(10,10,10)
# random_tensor

In [20]:
random_tensor.ndim

3

In [21]:
# Creating a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3))  # height, width, colour channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

# Zeros and ones

In [22]:
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [23]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [24]:
ones.dtype

torch.float32

In [25]:
random_tensor.dtype

torch.float32

# Creating a range of tensors and tensors-like

In [26]:
# Use torch.arange()

one_to_ten = torch.arange(start=0, end=11, step=1)
one_to_ten

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
# Creating tensor like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [28]:
ten_ones = torch.ones_like(input=one_to_ten)
ten_ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

# Tensor datatypes

**Note**: Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on right Device

In [29]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float32,   # What datatype is the tensor (e.g. float32 or float64) # it healps in Precision computing
                               device=None,   # What device is your tensor on
                               requires_grad=False)   # Whether or not to track gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [30]:
float_32_tensor.dtype

torch.float32

In [31]:
float_16_tensor = float_32_tensor.type(torch.float16)     # We converted the float 32 tensor to float 16 tensor.
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [32]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.long)
int_32_tensor

tensor([3, 6, 9])

In [33]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from Tensors "Attribute"

1. Tensors not right datatype - to do get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors not on right Device - to get device from a tensor, can use `tensor.device`

In [34]:
# Create a tensor

some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.7342, 0.6443, 0.2918, 0.7891],
        [0.9371, 0.2184, 0.2709, 0.6129],
        [0.6815, 0.5344, 0.6086, 0.0019]])

In [35]:
# Find the information about the Tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"shape of tensor: {some_tensor.shape}")    # print(f"shape of tensor: {some_tensor.size()}")
print(f"Device of tensor: {some_tensor.device}")

tensor([[0.7342, 0.6443, 0.2918, 0.7891],
        [0.9371, 0.2184, 0.2709, 0.6129],
        [0.6815, 0.5344, 0.6086, 0.0019]])
Datatype of tensor: torch.float32
shape of tensor: torch.Size([3, 4])
Device of tensor: cpu


# Manipulating Tensors (tensors operations)

Tensor Operation includes:
* Addition
* Substraction
* Multiplication (element-wise)
* Division
* Matrix - Multiplication

In [48]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [49]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [50]:
# Substraction 10
tensor - 10

tensor([-9, -8, -7])

In [51]:
# Inbuilt function using
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [52]:
torch.add(tensor, 10)

tensor([11, 12, 13])

# Matrix Multiplication

Two main ways of performing multiplication in neural networks and deep learning:

1. Element-wise multiplication
2. Matrix multiplication (dot product)

There are two main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimensions** must match:
* `(3,2) @ (3,2)` won't work
* `(2,3) @ (3,2)` will work
* `(3,2) @ (2,3)` will work

In [66]:
# 1. Elementwise Multiplication
tensor = torch.randint(low=1, high=5, size=[3])

print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([4, 1, 3]) * tensor([4, 1, 3])
Equals: tensor([16,  1,  9])


In [67]:
# 2. Matrix multiplication [dot product]
torch.matmul(tensor, tensor)

tensor(26)

In [68]:
tensor @ tensor

tensor(26)

In [69]:
torch.matmul(input=torch.rand(3,2), other=torch.rand(2,3))

tensor([[0.2809, 0.5753, 0.2027],
        [0.2974, 0.6037, 0.2120],
        [0.4481, 0.6192, 0.1814]])