<a href="https://colab.research.google.com/github/KrishDhanani/PyTorch_DeepLearning/blob/main/001_PyTorch_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

This is **First** file of course :)

In [47]:
print("I'm excited to write PyTorch code!")

I'm excited to write PyTorch code!


In [48]:
import torch
print(torch.__version__)
# You can chnage btw CPU, GPU AND TPU: Runtime -> Change runtime type

2.11.0+cpu


In [49]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## Introduction to Tensors

### Creating tensors


PyTorch tensors are created using 'torch.Tensor()' -= https://docs.pytorch.org/docs/main/tensors.html

In [50]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [51]:
scalar.ndim

0

In [52]:
# Get tensor back as python int
scalar.item()

7

In [53]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [54]:
vector.ndim

1

In [55]:
vector.shape

torch.Size([2])

In [56]:
# MATRIX
MATRIX = torch.tensor([[7,8],
                       [8,9]])
MATRIX

tensor([[7, 8],
        [8, 9]])

In [57]:
MATRIX.ndim   # Dimentions like square breacket in the tensor

2

In [58]:
MATRIX[0]

tensor([7, 8])

In [59]:
MATRIX.shape

torch.Size([2, 2])

In [60]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [3,4,5],
                        [4,5,6]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 4, 5],
         [4, 5, 6]]])

In [61]:
TENSOR.ndim

3

In [62]:
TENSOR.shape

torch.Size([1, 3, 3])

# Random Tensors

Why random tensors?

Random tensors are important bcs the way many neural network learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data ->update random numbers -> look at data -> update random numbers`

Torch random tensors - https://docs.pytorch.org/docs/main/generated/torch.rand.html#torch-rand

In [63]:
# Creat Random Tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.9472, 0.9625, 0.7065, 0.4916],
        [0.9093, 0.5710, 0.5191, 0.4306],
        [0.3025, 0.5578, 0.6196, 0.3562]])

In [64]:
random_tensor.ndim

2

In [65]:
random_tensor = torch.rand(10,10,10)
# random_tensor

In [66]:
random_tensor.ndim

3

In [67]:
# Creating a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3))  # height, width, colour channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

# Zeros and ones

In [68]:
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [69]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [70]:
ones.dtype

torch.float32

In [71]:
random_tensor.dtype

torch.float32

# Creating a range of tensors and tensors-like

In [72]:
# Use torch.arange()

one_to_ten = torch.arange(start=0, end=11, step=1)
one_to_ten

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [73]:
# Creating tensor like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [74]:
ten_ones = torch.ones_like(input=one_to_ten)
ten_ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

# Tensor datatypes

**Note**: Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on right Device

In [75]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float32,   # What datatype is the tensor (e.g. float32 or float64) # it healps in Precision computing
                               device=None,   # What device is your tensor on
                               requires_grad=False)   # Whether or not to track gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [76]:
float_32_tensor.dtype

torch.float32

In [77]:
float_16_tensor = float_32_tensor.type(torch.float16)     # We converted the float 32 tensor to float 16 tensor.
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [78]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.long)
int_32_tensor

tensor([3, 6, 9])

In [79]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from Tensors "Attribute"

1. Tensors not right datatype - to do get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors not on right Device - to get device from a tensor, can use `tensor.device`

In [80]:
# Create a tensor

some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.3827, 0.1751, 0.7395, 0.7882],
        [0.8280, 0.6782, 0.7804, 0.9322],
        [0.4736, 0.6299, 0.9158, 0.9055]])

In [81]:
# Find the information about the Tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"shape of tensor: {some_tensor.shape}")    # print(f"shape of tensor: {some_tensor.size()}")
print(f"Device of tensor: {some_tensor.device}")

tensor([[0.3827, 0.1751, 0.7395, 0.7882],
        [0.8280, 0.6782, 0.7804, 0.9322],
        [0.4736, 0.6299, 0.9158, 0.9055]])
Datatype of tensor: torch.float32
shape of tensor: torch.Size([3, 4])
Device of tensor: cpu


# Manipulating Tensors (tensors operations)

Tensor Operation includes:
* Addition
* Substraction
* Multiplication (element-wise)
* Division
* Matrix - Multiplication

In [82]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [83]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [84]:
# Substraction 10
tensor - 10

tensor([-9, -8, -7])

In [85]:
# Inbuilt function using
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [86]:
torch.add(tensor, 10)

tensor([11, 12, 13])

# Matrix Multiplication

Two main ways of performing multiplication in neural networks and deep learning:

1. Element-wise multiplication
2. Matrix multiplication (dot product)

There are two main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimensions** must match:
* `(3,2) @ (3,2)` won't work
* `(2,3) @ (3,2)` will work
* `(3,2) @ (2,3)` will work

In [87]:
# 1. Elementwise Multiplication
tensor = torch.randint(low=1, high=5, size=[3])

print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([4, 1, 2]) * tensor([4, 1, 2])
Equals: tensor([16,  1,  4])


In [88]:
# 2. Matrix multiplication [dot product]
torch.matmul(tensor, tensor)

tensor(21)

In [89]:
tensor @ tensor

tensor(21)

In [90]:
torch.matmul(input=torch.rand(3,2), other=torch.rand(2,3))

tensor([[0.0910, 0.1641, 0.1404],
        [0.5256, 0.5571, 0.6788],
        [0.4868, 0.8167, 0.7301]])

In [91]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 255 µs, sys: 35 µs, total: 290 µs
Wall time: 240 µs


tensor(21)

# One of the most common errors in deep learning: shape errors

In [92]:
# Shape for matrix multiplication

tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])

tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])

# torch.mm(tensor_A, tensor_B)   # torch.mm is same as torch.matmul (it's an alice for matmul)
torch.matmul(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
tensor_A.shape , tensor_B.shape

# Transpose

To fix out tensor shape issue, we can manipulate the shape of our tensors using a **transponse**.

A **transponse** switches the axes or dimensions of a given tensor.

In [93]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [94]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [95]:
# The matrix multiplication works when tensor_B is transposed

print(f"Original shape: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shape: tensor_A = {tensor_A.shape} (same shape as above), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shape: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shape: tensor_A = torch.Size([3, 2]) (same shape as above), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


## Finding the min, max, mean, sum etc (tensor aggregation)

In [102]:
# Creating tensor
x = torch.arange(0, 100, 10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [99]:
# Min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [100]:
# Max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [105]:
# Mean: torch.mean() function requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [106]:
# Sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

# Finding the positional min and max

In [107]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [108]:
# Find the position in tensor that has the minimum value with argmin() -> which return the index of that data which has lowest value among all/
x.argmin()

tensor(0)

In [109]:
x[0]

tensor(0)

In [110]:
# Find the position in tensor that has the maximum value with argmax() -> which returns the index of that data which has largest value among all data.
x.argmax()

tensor(9)

In [111]:
x[9]

tensor(90)

# Reshaping, Staking, Squeezing and unsqueezing tensors

- Reshaping - reshapes an input tensor to a defined shape
- View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
- Staking - combine multiple tensors on top of each othe (vstack) or side by side (hstack)
- Squeeze -remove all `1` dimensions from a tensor
- Unsqueeze - add a `1` dimension to a target tensor
- Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [123]:
# Lets create tensor
import torch

x = torch.arange(1,11)
x, x.shape

(tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]), torch.Size([10]))

In [124]:
# Add an extra dimension
x_reshaped = x.reshape(5,2)
x_reshaped, x_reshaped.shape

(tensor([[ 1,  2],
         [ 3,  4],
         [ 5,  6],
         [ 7,  8],
         [ 9, 10]]),
 torch.Size([5, 2]))

In [127]:
# Change the View : view is just sharing original memory of tensor
z = x.view(1, 10)
z, z.shape

(tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]]), torch.Size([1, 10]))

In [128]:
# Changing z changes x (happening of sharing same memory)
z[:, 0] = 5
z, x

(tensor([[ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10]]),
 tensor([ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10]))

In [136]:
# Stack tensoprs on top of each other
x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked

tensor([[ 5,  5,  5,  5],
        [ 2,  2,  2,  2],
        [ 3,  3,  3,  3],
        [ 4,  4,  4,  4],
        [ 5,  5,  5,  5],
        [ 6,  6,  6,  6],
        [ 7,  7,  7,  7],
        [ 8,  8,  8,  8],
        [ 9,  9,  9,  9],
        [10, 10, 10, 10]])

In [137]:
# Do by your self hstack and vstack

In [158]:
# Squeeze and Unsqueeze

# torch.Squeeze(): removes all single dimensions from a target tensor
y = torch.arange(1,9)
y, y.shape  # Previous tensor looks and shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8]), torch.Size([8]))

In [159]:
y_squeezed = y.squeeze()   # After Squeeze looks like
y_squeezed

tensor([1, 2, 3, 4, 5, 6, 7, 8])

In [160]:
y.squeeze().shape   # After Squeezing shape

torch.Size([8])

In [161]:
# torch.unsqueeze() - adds a single dimensions to a target at a specific dim (dimensions)

In [162]:
y_unsqueezed = y_squeezed.unsqueeze(dim=0)
y_unsqueezed

tensor([[1, 2, 3, 4, 5, 6, 7, 8]])

In [181]:
# Permute: torch.permute() -> It's kind of rearanging the tensor dimension
# Also it's kind of view of original tensor like sharing the same memory like view methode
# Using this thing for images
x = torch.randn(2, 3, 5)
x.shape

torch.Size([2, 3, 5])

In [182]:
permuted_x = torch.permute(x, (2, 0, 1)).shape   # It's taking firstly tensor then by the indaxing of shape of reshaping the original shape
permuted_x

torch.Size([5, 2, 3])

In [184]:
print(f"Initial value from original tensor x at index 0,0,0: {x[0, 0, 0]}")
x[0,0,0] = 1
permuted_x = torch.permute(x, (2, 0, 1)) # Re-assign permuted_x to be the actual permuted tensor
print(f"After changing value from original tensor x at index 0,0,0: {permuted_x[0, 0, 0]}")

Initial value from original tensor x at index 0,0,0: 1.0
After changing value from original tensor x at index 0,0,0: 1.0
