This is **First** file of course :)

In [2]:
print("I'm excited to write PyTorch code!")

I'm excited to write PyTorch code!


In [3]:
import torch
print(torch.__version__)
# You can chnage btw CPU, GPU AND TPU: Runtime -> Change runtime type

2.11.0+cu128


In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## Introduction to Tensors

### Creating tensors


PyTorch tensors are created using 'torch.Tensor()' -= https://docs.pytorch.org/docs/main/tensors.html

In [5]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [6]:
scalar.ndim

0

In [7]:
# Get tensor back as python int
scalar.item()

7

In [8]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [9]:
vector.ndim

1

In [10]:
vector.shape

torch.Size([2])

In [11]:
# MATRIX
MATRIX = torch.tensor([[7,8],
                       [8,9]])
MATRIX

tensor([[7, 8],
        [8, 9]])

In [12]:
MATRIX.ndim   # Dimentions like square breacket in the tensor

2

In [13]:
MATRIX[0]

tensor([7, 8])

In [14]:
MATRIX.shape

torch.Size([2, 2])

In [15]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [3,4,5],
                        [4,5,6]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 4, 5],
         [4, 5, 6]]])

In [16]:
TENSOR.ndim

3

In [17]:
TENSOR.shape

torch.Size([1, 3, 3])

# Random Tensors

Why random tensors?

Random tensors are important bcs the way many neural network learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data ->update random numbers -> look at data -> update random numbers`

Torch random tensors - https://docs.pytorch.org/docs/main/generated/torch.rand.html#torch-rand

In [18]:
# Creat Random Tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.7143, 0.8973, 0.0109, 0.3405],
        [0.4590, 0.1449, 0.9182, 0.9124],
        [0.0106, 0.4612, 0.6633, 0.5633]])

In [19]:
random_tensor.ndim

2

In [20]:
random_tensor = torch.rand(10,10,10)
# random_tensor

In [21]:
random_tensor.ndim

3

In [22]:
# Creating a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3))  # height, width, colour channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

# Zeros and ones

In [23]:
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [24]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [25]:
ones.dtype

torch.float32

In [26]:
random_tensor.dtype

torch.float32

# Creating a range of tensors and tensors-like

In [27]:
# Use torch.arange()

one_to_ten = torch.arange(start=0, end=11, step=1)
one_to_ten

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [28]:
# Creating tensor like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [29]:
ten_ones = torch.ones_like(input=one_to_ten)
ten_ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

# Tensor datatypes

**Note**: Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on right Device

In [30]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float32,   # What datatype is the tensor (e.g. float32 or float64) # it healps in Precision computing
                               device=None,   # What device is your tensor on
                               requires_grad=False)   # Whether or not to track gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [31]:
float_32_tensor.dtype

torch.float32

In [32]:
float_16_tensor = float_32_tensor.type(torch.float16)     # We converted the float 32 tensor to float 16 tensor.
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [33]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.long)
int_32_tensor

tensor([3, 6, 9])

In [34]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from Tensors "Attribute"

1. Tensors not right datatype - to do get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors not on right Device - to get device from a tensor, can use `tensor.device`

In [35]:
# Create a tensor

some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.0709, 0.4132, 0.1938, 0.3105],
        [0.6924, 0.6085, 0.7021, 0.1787],
        [0.2139, 0.7150, 0.3101, 0.3136]])

In [36]:
# Find the information about the Tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"shape of tensor: {some_tensor.shape}")    # print(f"shape of tensor: {some_tensor.size()}")
print(f"Device of tensor: {some_tensor.device}")

tensor([[0.0709, 0.4132, 0.1938, 0.3105],
        [0.6924, 0.6085, 0.7021, 0.1787],
        [0.2139, 0.7150, 0.3101, 0.3136]])
Datatype of tensor: torch.float32
shape of tensor: torch.Size([3, 4])
Device of tensor: cpu


# Manipulating Tensors (tensors operations)

Tensor Operation includes:
* Addition
* Substraction
* Multiplication (element-wise)
* Division
* Matrix - Multiplication

In [37]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [38]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [39]:
# Substraction 10
tensor - 10

tensor([-9, -8, -7])

In [40]:
# Inbuilt function using
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [41]:
torch.add(tensor, 10)

tensor([11, 12, 13])

# Matrix Multiplication

Two main ways of performing multiplication in neural networks and deep learning:

1. Element-wise multiplication
2. Matrix multiplication (dot product)

There are two main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimensions** must match:
* `(3,2) @ (3,2)` won't work
* `(2,3) @ (3,2)` will work
* `(3,2) @ (2,3)` will work

In [42]:
# 1. Elementwise Multiplication
tensor = torch.randint(low=1, high=5, size=[3])

print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([3, 3, 1]) * tensor([3, 3, 1])
Equals: tensor([9, 9, 1])


In [43]:
# 2. Matrix multiplication [dot product]
torch.matmul(tensor, tensor)

tensor(19)

In [44]:
tensor @ tensor

tensor(19)

In [45]:
torch.matmul(input=torch.rand(3,2), other=torch.rand(2,3))

tensor([[0.5721, 0.4604, 0.3891],
        [0.3262, 0.2033, 0.2207],
        [1.2179, 0.4795, 0.8184]])

In [46]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 771 µs, sys: 0 ns, total: 771 µs
Wall time: 614 µs


tensor(19)

# One of the most common errors in deep learning: shape errors

In [47]:
# Shape for matrix multiplication

tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])

tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])

# torch.mm(tensor_A, tensor_B)   # torch.mm is same as torch.matmul (it's an alice for matmul)
# torch.matmul(tensor_A, tensor_B)

In [48]:
tensor_A.shape , tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

# Transpose

To fix out tensor shape issue, we can manipulate the shape of our tensors using a **transponse**.

A **transponse** switches the axes or dimensions of a given tensor.

In [49]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [50]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [51]:
# The matrix multiplication works when tensor_B is transposed

print(f"Original shape: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shape: tensor_A = {tensor_A.shape} (same shape as above), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shape: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shape: tensor_A = torch.Size([3, 2]) (same shape as above), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


## Finding the min, max, mean, sum etc (tensor aggregation)

In [52]:
# Creating tensor
x = torch.arange(0, 100, 10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [53]:
# Min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [54]:
# Max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [55]:
# Mean: torch.mean() function requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [56]:
# Sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

# Finding the positional min and max

In [57]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [58]:
# Find the position in tensor that has the minimum value with argmin() -> which return the index of that data which has lowest value among all/
x.argmin()

tensor(0)

In [59]:
x[0]

tensor(0)

In [60]:
# Find the position in tensor that has the maximum value with argmax() -> which returns the index of that data which has largest value among all data.
x.argmax()

tensor(9)

In [61]:
x[9]

tensor(90)

# Reshaping, Staking, Squeezing and unsqueezing tensors

- Reshaping - reshapes an input tensor to a defined shape
- View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
- Staking - combine multiple tensors on top of each othe (vstack) or side by side (hstack)
- Squeeze -remove all `1` dimensions from a tensor
- Unsqueeze - add a `1` dimension to a target tensor
- Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [62]:
# Lets create tensor
import torch

x = torch.arange(1,11)
x, x.shape

(tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]), torch.Size([10]))

In [63]:
# Add an extra dimension
x_reshaped = x.reshape(5,2)
x_reshaped, x_reshaped.shape

(tensor([[ 1,  2],
         [ 3,  4],
         [ 5,  6],
         [ 7,  8],
         [ 9, 10]]),
 torch.Size([5, 2]))

In [64]:
# Change the View : view is just sharing original memory of tensor
z = x.view(1, 10)
z, z.shape

(tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]]), torch.Size([1, 10]))

In [65]:
# Changing z changes x (happening of sharing same memory)
z[:, 0] = 5
z, x

(tensor([[ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10]]),
 tensor([ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10]))

In [66]:
# Stack tensoprs on top of each other
x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked

tensor([[ 5,  5,  5,  5],
        [ 2,  2,  2,  2],
        [ 3,  3,  3,  3],
        [ 4,  4,  4,  4],
        [ 5,  5,  5,  5],
        [ 6,  6,  6,  6],
        [ 7,  7,  7,  7],
        [ 8,  8,  8,  8],
        [ 9,  9,  9,  9],
        [10, 10, 10, 10]])

In [67]:
# Do by your self hstack and vstack

In [68]:
# Squeeze and Unsqueeze

# torch.Squeeze(): removes all single dimensions from a target tensor
y = torch.arange(1,9)
y, y.shape  # Previous tensor looks and shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8]), torch.Size([8]))

In [69]:
y_squeezed = y.squeeze()   # After Squeeze looks like
y_squeezed

tensor([1, 2, 3, 4, 5, 6, 7, 8])

In [70]:
y.squeeze().shape   # After Squeezing shape

torch.Size([8])

In [71]:
# torch.unsqueeze() - adds a single dimensions to a target at a specific dim (dimensions)

In [72]:
y_unsqueezed = y_squeezed.unsqueeze(dim=0)
y_unsqueezed

tensor([[1, 2, 3, 4, 5, 6, 7, 8]])

In [73]:
# Permute: torch.permute() -> It's kind of rearanging the tensor dimension
# Also it's kind of view of original tensor like sharing the same memory like view methode
# Using this thing for images
x = torch.randn(2, 3, 5)
x.shape

torch.Size([2, 3, 5])

In [74]:
permuted_x = torch.permute(x, (2, 0, 1)).shape   # It's taking firstly tensor then by the indaxing of shape of reshaping the original shape
permuted_x

torch.Size([5, 2, 3])

In [75]:
print(f"Initial value from original tensor x at index 0,0,0: {x[0, 0, 0]}")
x[0,0,0] = 1
permuted_x = torch.permute(x, (2, 0, 1)) # Re-assign permuted_x to be the actual permuted tensor
print(f"After changing value from original tensor x at index 0,0,0: {permuted_x[0, 0, 0]}")

Initial value from original tensor x at index 0,0,0: 0.654466986656189
After changing value from original tensor x at index 0,0,0: 1.0


# Indexing (Selecting data from tensors)

Indexing with pytorch is similar to indexing with NumPy.

In [76]:
# Create torch
import torch
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [77]:
# Let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [78]:
# Let's index on our middle bracket (dim=1)
x[0][0]

tensor([1, 2, 3])

In [79]:
# Let's index on the most inner breacket
x[0][0][0], x[0,0,0]    # both way you can write

(tensor(1), tensor(1))

In [80]:
x[:, :, 0]

tensor([[1, 4, 7]])

In [81]:
# to get 9
x[0, 2, 2]

tensor(9)

In [82]:
# You can also use ":" to select "all" of a target dimensions
x[:, 0]

tensor([[1, 2, 3]])

In [83]:
# Get all values of zeros and first dimensions but only index 1 of 2nd dimensions
x[:, :, 1]

tensor([[2, 5, 8]])

In [84]:
# What if I want all values of row 3
x[0, 2, :]

tensor([7, 8, 9])

In [85]:
# What if i want 3 column
x[0, :, 2]

tensor([3, 6, 9])

# Pytorch tensors & NumPy

Numpy is a popular scientific Pytorch numerical computing library and because of that Pytorch has functionality to interact with it.

* Data in Numpy, want in Pytorch tensor -> `torch.from_numpy(ndarray)`

* Pytorch tensor -> Numpy -> `torch.Tensor.Numpy()`

In [86]:
# Numpy array to tensor
import numpy as np
import torch

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)  # Warning: when converting from numpy to pytorch, pytorch reflect's numpy's default datatype of float64 unless specified otherwise.
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [87]:
array.dtype

dtype('float64')

In [88]:
tensor.dtype

torch.float64

In [89]:
torch.arange(1.0, 8.0).dtype

torch.float32

In [90]:
# Change the value of array, what will this do to `tensor`?
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [91]:
# Tensor to Numpy array
tensor = torch.ones(5)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1.]), array([1., 1., 1., 1., 1.], dtype=float32))

In [92]:
numpy_tensor.dtype

dtype('float32')

In [93]:
# Change the tensor, What happens to 'numpy_tensor'?
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2.]), array([1., 1., 1., 1., 1.], dtype=float32))

# Reproducibility (trying to take random out of random)

In short how a neural network learns:
`start with random number -> tensor operation -> update a random number to try and make them better representation of the data -> again -> again -> again...`

To reduce the randomness in neural networks and PyTorch comes the concept of a **random seed.**

Essentially what the random seed does is "flavour" the randomness.

In [94]:
import torch

# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.3540, 0.4407, 0.2789, 0.3292],
        [0.2507, 0.3455, 0.2413, 0.1605],
        [0.2877, 0.1719, 0.0157, 0.2689]])
tensor([[0.3259, 0.3633, 0.3186, 0.4199],
        [0.5063, 0.6829, 0.6261, 0.2946],
        [0.9445, 0.0625, 0.9097, 0.3239]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [95]:
# Let's make some random but reproducible tensors
import torch

# set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED) #
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED) #
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)


tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


# Running tensors and PyTorch objects on the GPUs (and making faster computation)

GPUs = Faster computation on number, thanks to CUDA + NVIDIA hardware + PyTorch working behind the scenes to make everything hunky dorgy(good)

### 1. Getting GPU

1. Easiest - Use Google Colab for a free GPU (options to upgrade as well)
2. Use your own GPU - takes a liitle bit of set-up and require some investment and have too much options   
3. Use cloud computing - GCP, AWS, Azure, these are services allow you to compute on the cloud and access them

In [96]:
!nvidia-smi

Mon Jun  1 18:21:06 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.82.07              Driver Version: 580.82.07      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   44C    P8              9W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

### 2. Check for GPU access with PyTorch

In [97]:
import torch

torch.cuda.is_available()

True

For python it's capable of running compute on the GPU or CPU, it's best practice to setup device agnostic code

E.g. run on GPU if available otherwise in CPU

In [98]:
# Setup device agtnostic code
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cuda'

In [99]:
# Count number of devices
torch.cuda.device_count()

1

### 3. Puting tensors and model on GPU

The reason we want our tensors/models on the GPU is because using a GPU results in faster computation.


In [100]:
# Create tensor and default is on CPU
tensor = torch.tensor([1,2,3])

# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [101]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### 4. Moving tensors back to the CPU

In [102]:
# If tensor is on GPU, can't transform to NumPy
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [103]:
# To fix the GPU tensor with NumPy issue, we can first set it to the GPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [104]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')