# Exercise of 001 PyTorch Fundamental

 1. Documentation reading - A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness). See the documentation on torch.Tensor and for torch.cuda.

2. Create a random tensor with shape (7, 7).

In [1]:
import torch

tensor = torch.rand([7,7])
tensor

tensor([[0.7656, 0.5427, 0.4706, 0.4598, 0.8905, 0.8320, 0.6796],
        [0.4752, 0.3458, 0.2555, 0.8139, 0.4985, 0.6158, 0.4593],
        [0.5695, 0.4280, 0.1873, 0.4740, 0.3654, 0.8019, 0.3604],
        [0.2054, 0.5525, 0.1511, 0.7354, 0.6172, 0.5673, 0.9320],
        [0.3629, 0.2703, 0.6239, 0.4432, 0.9021, 0.3086, 0.2410],
        [0.6394, 0.8354, 0.5989, 0.3983, 0.0804, 0.1009, 0.0419],
        [0.1402, 0.8052, 0.0378, 0.4856, 0.7191, 0.0637, 0.7063]])

3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).

In [2]:
random_tensor = torch.rand([1,7])
torch.matmul(tensor, random_tensor.T)

tensor([[2.9792],
        [2.2209],
        [1.9614],
        [2.5697],
        [1.9857],
        [1.4806],
        [2.2476]])

4. Set the random seed to 0 and do exercises 2 & 3 over again.

In [3]:
RANDOM_SEED = 0
torch.manual_seed(RANDOM_SEED)
tensor = torch.rand([7,7])
print(tensor)

RANDOM_SEED = 0
torch.manual_seed(RANDOM_SEED)
tensor_1 = torch.rand([1,7])
torch.matmul(tensor, tensor_1.T)

tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]])


tensor([[1.5985],
        [1.1173],
        [1.2741],
        [1.6838],
        [0.8279],
        [1.0347],
        [1.2498]])

5. Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent? (hint: you'll need to look into the documentation for torch.cuda for this one). If there is, set the GPU random seed to 1234.

In [4]:
torch.cuda.is_available()

True

In [5]:
torch.cuda.manual_seed(1234)
# If you are working with a multi-GPU model, this function is insufficient to get determinism.
# To seed all GPUs, use manual_seed_all().

6. Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed).

In [9]:
MANUAL_SEED = 1234
torch.manual_seed(MANUAL_SEED)
tensor_1 = torch.rand([2,3])

torch.manual_seed(MANUAL_SEED)
tensor_1 = torch.rand([2,3])

device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(f"We have device: {device}")

tensor_1_on_gpu = tensor.to(device)
tensor_2_on_gpu = tensor.to(device)

print(f"{tensor_1_on_gpu.device} & {tensor_2_on_gpu.device}")

We have device: cuda
cuda:0 & cuda:0


7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

In [12]:
%%time
multiplied_tensors = torch.matmul(tensor_1_on_gpu, tensor_2_on_gpu.T)
multiplied_tensors

CPU times: user 797 µs, sys: 0 ns, total: 797 µs
Wall time: 510 µs


tensor([[1.5985, 1.1173, 1.2741, 1.6838, 0.8279, 1.0347, 1.2498],
        [1.1173, 1.7231, 1.4061, 1.9499, 0.9564, 1.3146, 1.1037],
        [1.2741, 1.4061, 2.0522, 1.8029, 1.4137, 1.7786, 1.0244],
        [1.6838, 1.9499, 1.8029, 3.1500, 1.3352, 2.1484, 1.9877],
        [0.8279, 0.9564, 1.4137, 1.3352, 1.2619, 1.3505, 0.7881],
        [1.0347, 1.3146, 1.7786, 2.1484, 1.3505, 2.3192, 1.4202],
        [1.2498, 1.1037, 1.0244, 1.9877, 0.7881, 1.4202, 1.7923]],
       device='cuda:0')

8. Find the maximum and minimum values of the output of 7.

In [13]:
torch.argmin(multiplied_tensors)

tensor(34, device='cuda:0')

9. Find the maximum and minimum index values of the output of 7.

In [14]:
torch.argmax(multiplied_tensors)

tensor(24, device='cuda:0')

10. Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10).
Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

In [20]:
MANUAL_SEED = 7
torch.manual_seed(MANUAL_SEED)

tenor_1 = torch.rand([1,1,1,10])

tensor_2 = tensor_1.squeeze()

print(f"Tensor_1: {tensor_1} & Shape_of_Tensor_1:{tensor_1.shape}")
print(f"Tensor_2: {tensor_2} & Shape_of_Tensor_2:{tensor_2.shape}")

Tensor_1: tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]]) & Shape_of_Tensor_1:torch.Size([2, 3])
Tensor_2: tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]]) & Shape_of_Tensor_2:torch.Size([2, 3])


11. Extra-curriculum
Spend 1-hour going through the [PyTorch basics tutorial](https://pytorch.org/tutorials/beginner/basics/intro.html) (I'd recommend the [Quickstart](https://pytorch.org/tutorials/beginner/basics/quickstart_tutorial.html) and [Tensors](https://pytorch.org/tutorials/beginner/basics/tensorqs_tutorial.html) sections).
To learn more on how a tensor can represent data, see this video: [What's a tensor](https://youtu.be/f5liqUk0ZTw)?